
"""
Complete collection of physical constants for use in physics calculations.
Includes SI base constants, particle physics, electromagnetism, thermodynamics, 
atomic physics, nuclear physics, astronomical constants, and various unit systems.
"""

import math

# SI Base Physical Constants
SPEED_OF_LIGHT = 2.99792458e8
PLANCK_CONSTANT = 6.62607015e-34
REDUCED_PLANCK = PLANCK_CONSTANT / (2 * math.pi)
GRAVITATIONAL_CONSTANT = 6.67430e-11
ELEMENTARY_CHARGE = 1.602176634e-19
AVOGADRO_NUMBER = 6.02214076e23
BOLTZMANN_CONSTANT = 1.380649e-23
GAS_CONSTANT = 8.314462618
VACUUM_PERMITTIVITY = 8.8541878128e-12
VACUUM_PERMEABILITY = 1.25663706212e-6
COULOMB_CONSTANT = 1 / (4 * math.pi * VACUUM_PERMITTIVITY)
STEFAN_BOLTZMANN_CONSTANT = 5.670374419e-8
WIEN_DISPLACEMENT_CONSTANT = 2.897771955e-3
FINE_STRUCTURE_CONSTANT = 7.2973525693e-3
RYDBERG_CONSTANT = 10973731.568160
THOMSON_CROSS_SECTION = 6.6524587321e-29
FARADAY_CONSTANT = 96485.33212
ELECTRON_CHARGE_TO_MASS = 1.75882001076e11
ATMOSPHERIC_PRESSURE = 101325
EARTH_GRAVITY = 9.80665
STANDARD_TEMPERATURE = 273.15
STANDARD_PRESSURE = 101325

# Fundamental Particle Masses
ELECTRON_MASS = 9.1093837015e-31
PROTON_MASS = 1.67262192369e-27
NEUTRON_MASS = 1.67492749804e-27
MUON_MASS = 1.883531627e-28
TAU_MASS = 3.16754e-27
ALPHA_PARTICLE_MASS = 6.6446573357e-27
DEUTERON_MASS = 3.3435837724e-27
TRITON_MASS = 5.0073567446e-27
HELION_MASS = 5.0064127796e-27

# Additional Particle Masses
PION_CHARGED_MASS = 2.48832e-28
PION_NEUTRAL_MASS = 2.40652e-28
KAON_CHARGED_MASS = 8.80355e-28
KAON_NEUTRAL_MASS = 8.87594e-28
LAMBDA_BARYON_MASS = 1.98748e-27
PROTON_CHARGE_RADIUS = 8.414e-16
NEUTRON_MAGNETIC_MOMENT = -9.6623651e-27

# Atomic Units and Chemistry
ATOMIC_MASS_UNIT = 1.66053906660e-27
BOHR_RADIUS = 5.29177210903e-11
ELECTRON_VOLT = 1.602176634e-19
HARTREE_ENERGY = 4.3597447222071e-18
MOLAR_GAS_CONSTANT = GAS_CONSTANT
ATOMIC_UNIT_OF_TIME = 2.4188843265857e-17
ATOMIC_UNIT_OF_VELOCITY = 2.18769126364e6
ATOMIC_UNIT_OF_ENERGY = HARTREE_ENERGY
ATOMIC_UNIT_OF_ELECTRIC_FIELD = 5.14220674763e11
ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL = 27.211386245988
ATOMIC_UNIT_OF_FORCE = 8.2387234983e-8
ATOMIC_UNIT_OF_MOMENTUM = 1.9928519141e-24

# Planck Units
PLANCK_LENGTH = 1.616255e-35
PLANCK_TIME = 5.391247e-44
PLANCK_MASS = 2.176434e-8
PLANCK_ENERGY = 1.956082e9
PLANCK_TEMPERATURE = 1.416784e32
PLANCK_CHARGE = 1.87554595641e-18
PLANCK_FORCE = 1.21027e44
PLANCK_POWER = 3.62831e52
PLANCK_DENSITY = 5.15500e96
PLANCK_PRESSURE = 4.63309e113
PLANCK_IMPEDANCE = 29.9792458

# Quantum Physics Constants
HC_IN_MEV_FM = REDUCED_PLANCK * SPEED_OF_LIGHT / (1e-15 * ELECTRON_VOLT * 1e6)
BOHR_MAGNETON = 9.274009994e-24
NUCLEAR_MAGNETON = 5.050783699e-27
MAGNETIC_FLUX_QUANTUM = 2.067833848e-15
COMPTON_WAVELENGTH_ELECTRON = 2.42631023867e-12
COMPTON_WAVELENGTH_PROTON = 1.32140985539e-15
COMPTON_WAVELENGTH_NEUTRON = 1.31959090481e-15
CLASSICAL_ELECTRON_RADIUS = 2.8179403262e-15
JOSEPHSON_CONSTANT = 4.835978484e14
VON_KLITZING_CONSTANT = 25812.80745
CONDUCTANCE_QUANTUM = 7.748091729e-5

# Electromagnetic Constants
VACUUM_IMPEDANCE = math.sqrt(VACUUM_PERMEABILITY / VACUUM_PERMITTIVITY)
FIRST_RADIATION_CONSTANT = 3.741771852e-16
SECOND_RADIATION_CONSTANT = 1.438776877e-2
RADIATION_DENSITY_CONSTANT = 7.5657e-16
ELECTRIC_CONSTANT = VACUUM_PERMITTIVITY
MAGNETIC_CONSTANT = VACUUM_PERMEABILITY

# Nuclear Physics Constants
NUCLEAR_RADIUS_CONSTANT = 1.2e-15
BINDING_ENERGY_PER_NUCLEON = 8.5
MASS_EXCESS_ELECTRON = 0.548579909e-3
MASS_EXCESS_PROTON = 7.28899e-3
MASS_EXCESS_NEUTRON = 8.66491e-3
NUCLEAR_MAGNETON_RATIO = NUCLEAR_MAGNETON / BOHR_MAGNETON

# Thermodynamic Constants
FIRST_RADIATION_CONSTANT_C1 = 2 * math.pi * PLANCK_CONSTANT * SPEED_OF_LIGHT**2
SECOND_RADIATION_CONSTANT_C2 = PLANCK_CONSTANT * SPEED_OF_LIGHT / BOLTZMANN_CONSTANT
MOLAR_VOLUME_IDEAL_GAS_STP = 2.241409e-2
LOSCHMIDT_CONSTANT = 2.686780111e25
SACKUR_TETRODE_CONSTANT = -1.15170753e-23
STEFAN_BOLTZMANN_SIGMA = STEFAN_BOLTZMANN_CONSTANT

# Astronomical Constants
SOLAR_MASS = 1.98847e30
EARTH_MASS = 5.9722e24
MOON_MASS = 7.342e22
JUPITER_MASS = 1.8982e27
SOLAR_RADIUS = 6.96e8
EARTH_RADIUS = 6.371e6
MOON_RADIUS = 1.737e6
ASTRONOMICAL_UNIT = 1.495978707e11
PARSEC = 3.0857e16
LIGHT_YEAR = 9.4607304725808e15
SOLAR_LUMINOSITY = 3.828e26
SOLAR_SURFACE_TEMPERATURE = 5778
HUBBLE_CONSTANT = 2.2e-18
CRITICAL_DENSITY_UNIVERSE = 9.47e-27
COSMIC_MICROWAVE_BACKGROUND_TEMP = 2.725

# Earth and Planetary Constants
EARTH_ORBITAL_VELOCITY = 29780
EARTH_ESCAPE_VELOCITY = 11180
EARTH_ROTATION_PERIOD = 86164.0905
EARTH_ORBITAL_PERIOD = 31558149.504
MOON_ORBITAL_PERIOD = 2.360592e6
MOON_DISTANCE = 3.844e8

# Conversion Factors
ATMOSPHERE_TO_PASCAL = 101325.0
BAR_TO_PASCAL = 1e5
TORR_TO_PASCAL = 133.322368
CALORIE_TO_JOULE = 4.184
BTU_TO_JOULE = 1055.05585
ELECTRON_VOLT_TO_JOULE = ELECTRON_VOLT
ANGSTROM_TO_METER = 1e-10
BARN_TO_SQUARE_METER = 1e-28
CURIE_TO_BECQUEREL = 3.7e10
ROENTGEN_TO_COULOMB_PER_KG = 2.58e-4

# Speed Conversions
SPEED_OF_LIGHT_KM_S = SPEED_OF_LIGHT / 1000
SPEED_OF_LIGHT_CM_S = SPEED_OF_LIGHT * 100
SPEED_OF_LIGHT_FT_S = SPEED_OF_LIGHT * 3.28084
SPEED_OF_LIGHT_MPH = SPEED_OF_LIGHT * 2.237

# Energy Conversions
HARTREE_TO_EV = HARTREE_ENERGY / ELECTRON_VOLT
RYDBERG_TO_EV = HARTREE_TO_EV / 2
JOULE_TO_EV = 1 / ELECTRON_VOLT
JOULE_TO_CALORIE = 1 / CALORIE_TO_JOULE

# Mass Conversions
ELECTRON_MASS_MEV = ELECTRON_MASS * SPEED_OF_LIGHT**2 / (ELECTRON_VOLT * 1e6)
PROTON_MASS_MEV = PROTON_MASS * SPEED_OF_LIGHT**2 / (ELECTRON_VOLT * 1e6)
NEUTRON_MASS_MEV = NEUTRON_MASS * SPEED_OF_LIGHT**2 / (ELECTRON_VOLT * 1e6)
ATOMIC_MASS_UNIT_MEV = ATOMIC_MASS_UNIT * SPEED_OF_LIGHT**2 / (ELECTRON_VOLT * 1e6)

# Natural Units
C_NATURAL = 1
HBAR_NATURAL = 1
K_BOLTZMANN_NATURAL = 1
G_NEWTON_NATURAL = 1

# CGS Units
SPEED_OF_LIGHT_CGS = SPEED_OF_LIGHT * 100
PLANCK_CONSTANT_CGS = PLANCK_CONSTANT * 1e7
BOLTZMANN_CONSTANT_CGS = BOLTZMANN_CONSTANT * 1e7
GRAVITATIONAL_CONSTANT_CGS = GRAVITATIONAL_CONSTANT * 1000
ELEMENTARY_CHARGE_CGS = ELEMENTARY_CHARGE * 2.998e9
ELECTRON_MASS_CGS = ELECTRON_MASS * 1000
PROTON_MASS_CGS = PROTON_MASS * 1000

# Mathematical Constants
PI = math.pi
E = math.e
GOLDEN_RATIO = (1 + math.sqrt(5)) / 2
EULER_GAMMA = 0.5772156649015329

# Derived Physical Constants
BOHR_VELOCITY = FINE_STRUCTURE_CONSTANT * SPEED_OF_LIGHT
HYDROGEN_GROUND_STATE_ENERGY = -13.6057
CLASSICAL_ELECTRON_ORBIT_FREQUENCY = 6.579e15
CHARACTERISTIC_IMPEDANCE_FREE_SPACE = math.sqrt(VACUUM_PERMEABILITY / VACUUM_PERMITTIVITY)
CYCLOTRON_FREQUENCY_ELECTRON = ELEMENTARY_CHARGE / ELECTRON_MASS

# Particle Physics Constants
W_BOSON_MASS = 1.43332e-25
Z_BOSON_MASS = 1.62531e-25
HIGGS_BOSON_MASS = 2.23e-25
TOP_QUARK_MASS = 3.08e-25
BOTTOM_QUARK_MASS = 7.53e-27
CHARM_QUARK_MASS = 2.31e-27
STRANGE_QUARK_MASS = 1.70e-28
UP_QUARK_MASS = 3.6e-30
DOWN_QUARK_MASS = 8.6e-30

# Standard Model Parameters
FERMI_COUPLING_CONSTANT = 1.1663787e-5
WEINBERG_ANGLE = 0.48290
QCD_SCALE = 3.56e-13
STRONG_COUPLING_CONSTANT = 0.1181

# Exported Constants
__all__ = [
    # SI Base Constants
    'SPEED_OF_LIGHT', 'PLANCK_CONSTANT', 'REDUCED_PLANCK', 'GRAVITATIONAL_CONSTANT',
    'ELEMENTARY_CHARGE', 'AVOGADRO_NUMBER', 'BOLTZMANN_CONSTANT', 'GAS_CONSTANT',
    'VACUUM_PERMITTIVITY', 'VACUUM_PERMEABILITY', 'COULOMB_CONSTANT',
    'STEFAN_BOLTZMANN_CONSTANT', 'WIEN_DISPLACEMENT_CONSTANT', 'FINE_STRUCTURE_CONSTANT',
    'RYDBERG_CONSTANT', 'THOMSON_CROSS_SECTION', 'FARADAY_CONSTANT',
    'ELECTRON_CHARGE_TO_MASS', 'ATMOSPHERIC_PRESSURE', 'EARTH_GRAVITY',
    'STANDARD_TEMPERATURE', 'STANDARD_PRESSURE',
    
    # Particle Masses
    'ELECTRON_MASS', 'PROTON_MASS', 'NEUTRON_MASS', 'MUON_MASS', 'TAU_MASS',
    'ALPHA_PARTICLE_MASS', 'DEUTERON_MASS', 'TRITON_MASS', 'HELION_MASS',
    'PION_CHARGED_MASS', 'PION_NEUTRAL_MASS', 'KAON_CHARGED_MASS', 'KAON_NEUTRAL_MASS',
    'LAMBDA_BARYON_MASS', 'PROTON_CHARGE_RADIUS', 'NEUTRON_MAGNETIC_MOMENT',
    
    # Atomic Units
    'ATOMIC_MASS_UNIT', 'BOHR_RADIUS', 'ELECTRON_VOLT', 'HARTREE_ENERGY',
    'MOLAR_GAS_CONSTANT', 'ATOMIC_UNIT_OF_TIME', 'ATOMIC_UNIT_OF_VELOCITY',
    'ATOMIC_UNIT_OF_ENERGY', 'ATOMIC_UNIT_OF_ELECTRIC_FIELD', 'ATOMIC_UNIT_OF_ELECTRIC_POTENTIAL',
    'ATOMIC_UNIT_OF_FORCE', 'ATOMIC_UNIT_OF_MOMENTUM',
    
    # Planck Units
    'PLANCK_LENGTH', 'PLANCK_TIME', 'PLANCK_MASS', 'PLANCK_ENERGY', 'PLANCK_TEMPERATURE',
    'PLANCK_CHARGE', 'PLANCK_FORCE', 'PLANCK_POWER', 'PLANCK_DENSITY', 'PLANCK_PRESSURE',
    'PLANCK_IMPEDANCE',
    
    # Quantum Constants
    'HC_IN_MEV_FM', 'BOHR_MAGNETON', 'NUCLEAR_MAGNETON', 'MAGNETIC_FLUX_QUANTUM',
    'COMPTON_WAVELENGTH_ELECTRON', 'COMPTON_WAVELENGTH_PROTON', 'COMPTON_WAVELENGTH_NEUTRON',
    'CLASSICAL_ELECTRON_RADIUS', 'JOSEPHSON_CONSTANT', 'VON_KLITZING_CONSTANT',
    'CONDUCTANCE_QUANTUM',
    
    # Electromagnetic Constants
    'VACUUM_IMPEDANCE', 'FIRST_RADIATION_CONSTANT', 'SECOND_RADIATION_CONSTANT',
    'RADIATION_DENSITY_CONSTANT', 'ELECTRIC_CONSTANT', 'MAGNETIC_CONSTANT',
    
    # Nuclear Constants
    'NUCLEAR_RADIUS_CONSTANT', 'BINDING_ENERGY_PER_NUCLEON', 'MASS_EXCESS_ELECTRON',
    'MASS_EXCESS_PROTON', 'MASS_EXCESS_NEUTRON', 'NUCLEAR_MAGNETON_RATIO',
    
    # Thermodynamic Constants
    'FIRST_RADIATION_CONSTANT_C1', 'SECOND_RADIATION_CONSTANT_C2', 'MOLAR_VOLUME_IDEAL_GAS_STP',
    'LOSCHMIDT_CONSTANT', 'SACKUR_TETRODE_CONSTANT', 'STEFAN_BOLTZMANN_SIGMA',
    
    # Astronomical Constants
    'SOLAR_MASS', 'EARTH_MASS', 'MOON_MASS', 'JUPITER_MASS', 'SOLAR_RADIUS', 'EARTH_RADIUS',
    'MOON_RADIUS', 'ASTRONOMICAL_UNIT', 'PARSEC', 'LIGHT_YEAR', 'SOLAR_LUMINOSITY',
    'SOLAR_SURFACE_TEMPERATURE', 'HUBBLE_CONSTANT', 'CRITICAL_DENSITY_UNIVERSE',
    'COSMIC_MICROWAVE_BACKGROUND_TEMP',
    
    # Earth and Planetary Constants
    'EARTH_ORBITAL_VELOCITY', 'EARTH_ESCAPE_VELOCITY', 'EARTH_ROTATION_PERIOD',
    'EARTH_ORBITAL_PERIOD', 'MOON_ORBITAL_PERIOD', 'MOON_DISTANCE',
    
    # Conversion Factors
    'ATMOSPHERE_TO_PASCAL', 'BAR_TO_PASCAL', 'TORR_TO_PASCAL', 'CALORIE_TO_JOULE',
    'BTU_TO_JOULE', 'ELECTRON_VOLT_TO_JOULE', 'ANGSTROM_TO_METER', 'BARN_TO_SQUARE_METER',
    'CURIE_TO_BECQUEREL', 'ROENTGEN_TO_COULOMB_PER_KG',
    
    # Speed Conversions
    'SPEED_OF_LIGHT_KM_S', 'SPEED_OF_LIGHT_CM_S', 'SPEED_OF_LIGHT_FT_S', 'SPEED_OF_LIGHT_MPH',
    
    # Energy Conversions
    'HARTREE_TO_EV', 'RYDBERG_TO_EV', 'JOULE_TO_EV', 'JOULE_TO_CALORIE',
    
    # Mass Conversions
    'ELECTRON_MASS_MEV', 'PROTON_MASS_MEV', 'NEUTRON_MASS_MEV', 'ATOMIC_MASS_UNIT_MEV',
    
    # Natural Units
    'C_NATURAL', 'HBAR_NATURAL', 'K_BOLTZMANN_NATURAL', 'G_NEWTON_NATURAL',
    
    # CGS Units
    'SPEED_OF_LIGHT_CGS', 'PLANCK_CONSTANT_CGS', 'BOLTZMANN_CONSTANT_CGS',
    'GRAVITATIONAL_CONSTANT_CGS', 'ELEMENTARY_CHARGE_CGS', 'ELECTRON_MASS_CGS',
    'PROTON_MASS_CGS',
    
    # Mathematical Constants
    'PI', 'E', 'GOLDEN_RATIO', 'EULER_GAMMA',
    
    # Derived Constants
    'BOHR_VELOCITY', 'HYDROGEN_GROUND_STATE_ENERGY', 'CLASSICAL_ELECTRON_ORBIT_FREQUENCY',
    'CHARACTERISTIC_IMPEDANCE_FREE_SPACE', 'CYCLOTRON_FREQUENCY_ELECTRON',
    
    # Particle Physics
    'W_BOSON_MASS', 'Z_BOSON_MASS', 'HIGGS_BOSON_MASS', 'TOP_QUARK_MASS', 'BOTTOM_QUARK_MASS',
    'CHARM_QUARK_MASS', 'STRANGE_QUARK_MASS', 'UP_QUARK_MASS', 'DOWN_QUARK_MASS',
    
    # Standard Model
    'FERMI_COUPLING_CONSTANT', 'WEINBERG_ANGLE', 'QCD_SCALE', 'STRONG_COUPLING_CONSTANT',
]

# Utility Functions

def convert_energy(value, from_unit, to_unit):
    """Convert energy between different units (J, eV, cal, BTU, etc.)"""
    conversions = {
        'J': 1.0,
        'eV': ELECTRON_VOLT,
        'cal': CALORIE_TO_JOULE,
        'BTU': BTU_TO_JOULE,
        'Hartree': HARTREE_ENERGY,
        'Rydberg': HARTREE_ENERGY / 2,
    }
    
    if from_unit not in conversions or to_unit not in conversions:
        raise ValueError(f"Unsupported unit. Available: {list(conversions.keys())}")
    
    joules = value * conversions[from_unit]
    return joules / conversions[to_unit]

def convert_mass(value, from_unit, to_unit):
    """Convert mass between different units (kg, g, u, MeV/c², etc.)"""
    conversions = {
        'kg': 1.0,
        'g': 1e-3,
        'u': ATOMIC_MASS_UNIT,
        'MeV/c²': ELECTRON_VOLT * 1e6 / SPEED_OF_LIGHT**2,
        'electron_mass': ELECTRON_MASS,
        'proton_mass': PROTON_MASS,
    }
    
    if from_unit not in conversions or to_unit not in conversions:
        raise ValueError(f"Unsupported unit. Available: {list(conversions.keys())}")
    
    kg = value * conversions[from_unit]
    return kg / conversions[to_unit]

def convert_length(value, from_unit, to_unit):
    """Convert length between different units (m, cm, Å, fm, etc.)"""
    conversions = {
        'm': 1.0,
        'cm': 1e-2,
        'mm': 1e-3,
        'μm': 1e-6,
        'nm': 1e-9,
        'Å': 1e-10,
        'pm': 1e-12,
        'fm': 1e-15,
        'bohr': BOHR_RADIUS,
        'planck': PLANCK_LENGTH,
    }
    
    if from_unit not in conversions or to_unit not in conversions:
        raise ValueError(f"Unsupported unit. Available: {list(conversions.keys())}")
    
    meters = value * conversions[from_unit]
    return meters / conversions[to_unit]

def natural_units_conversion(quantity, unit_type):
    """Convert to natural units where ℏ = c = kB = 1"""
    if unit_type == 'energy':
        return quantity / ELECTRON_VOLT
    elif unit_type == 'mass':
        return quantity * SPEED_OF_LIGHT**2 / ELECTRON_VOLT
    elif unit_type == 'length':
        return quantity / (REDUCED_PLANCK * SPEED_OF_LIGHT / ELECTRON_VOLT)
    elif unit_type == 'time':
        return quantity / (REDUCED_PLANCK / ELECTRON_VOLT)
    else:
        raise ValueError("Supported types: 'energy', 'mass', 'length', 'time'")

if __name__ == "__main__":
    print("Physics Constants Library")
    print("=" * 50)
    print(f"Speed of light: {SPEED_OF_LIGHT:.0f} m/s")
    print(f"Planck constant: {PLANCK_CONSTANT:.6e} J·s")
    print(f"Electron mass: {ELECTRON_MASS:.6e} kg = {ELECTRON_MASS_MEV:.6f} MeV/c²")
    print(f"Proton mass: {PROTON_MASS:.6e} kg = {PROTON_MASS_MEV:.6f} MeV/c²")
    print(f"Fine structure constant: {FINE_STRUCTURE_CONSTANT:.10f}")
    print(f"Bohr radius: {BOHR_RADIUS:.6e} m = {convert_length(BOHR_RADIUS, 'm', 'Å'):.4f} Å")
    
    print("\nConversion Examples:")
    print(f"1 eV = {convert_energy(1, 'eV', 'J'):.6e} J")
    print(f"1 u = {convert_mass(1, 'u', 'kg'):.6e} kg")
    print(f"1 Å = {convert_length(1, 'Å', 'm'):.2e} m")
    
    print(f"\nTotal constants exported: {len(__all__)}")
